wt2/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='blog-home'),
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'), #tells the urls the pk is an int. detail view expects it a pk
    path('post/new/', views.PostCreateView.as_view(), name='post-create'), #expects the template name to be appname_form
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='post-delete'), #expect a form template named post_confirm_delete

]

# looking for a template name -> <app>/<model>_<viewtype> -> blog/post_list.html

wt2/wt2/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views #for login and logout premade views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('register/', user_views.register,name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), #tell the view where the template is
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),#they are a class based views
    path('profile/', user_views.profile, name='profile'),
    path('user/<int:pk>/', user_views.UserDetailView.as_view(), name='user-detail')
]

if settings.DEBUG: #if in debug mode add this
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wt2/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now) #set date time only when post is created
    author = models.ForeignKey(User, on_delete='CASCADE') #FOREIGN KEY = ONE TO MANY, 1 author many posts

    def __str__(self):
        return self.title

    def get_absolute_url(self): #creates a path to a specific post to be directed to
        return reverse('blog:post-detail',kwargs={'pk':self.pk}) #return post-detail and the primary key of the post as variable pk.

wt2/blog/views.py
from django.shortcuts import render
from . import models
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin


#dummy data

#logic for home page
def home(request):
    context = {
        'posts': models.Post.objects.all() # select (*) from Posts
    }
    #any key in context can now iterate in the html file
    #for flow stream {% for post in posts %}, for variables use {{ post.title }}
    return render(request, 'blog/home.html', context) #takes a request and the template file


def about(request):
    return render(request, 'blog/about.html', context={'title': 'about'})


###################################################
##class based views##
##List,Detail,Create,Update,Delete and much more pre-made views.
###################################################

class PostListView(ListView):
    model = models.Post
    template_name = 'blog/home.html' #give it a manual url, need to define a content variable
    context_object_name = 'posts' #would be "object" otherwise
    ordering = ['-date_posted'] #will date the posts from newest to older (remove '-' in front for reverse order)


class PostDetailView(DetailView):
    model = models.Post


#the mixins is like a decorated for class based view - will redirect to login if not logged in
class PostCreateView(LoginRequiredMixin,CreateView):
    model = models.Post #automatically passes form
    fields = {'title', 'content'} #those will be the form fields

    #need to tell it who the author is in order to submit a form

    def form_valid(self, form):
        form.instance.author = self.request.user #the form you try to submit, set the author of the instance to be the user writing the post
        return super().form_valid(form)


#need to check if the person who wrote the post tries to edit it which is the UserPassesTestMixin
class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = models.Post
    fields = {'title','content'}

    def form_valid(self, form):
        form.instance.author = self.request.user #the form you try to submit, set the author of the instance to be the user writing the post
        return super().form_valid(form)

    def test_func(self):
        post =self.get_object() #get the post we're trying to edit

        if self.request.user == post.author: #checks if the author post is the same as the editing author
            return True
        else:
            return False


class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = models.Post
    success_url = '/' #send them to homepage if deleted

    def test_func(self):
        post =self.get_object() #get the post we're trying to edit

        if self.request.user == post.author: #checks if the author post is the same as the editing author
            return True
        else:
            return False

wt2/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>About Page!</h1>
{% endblock %}

wt2/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
    <title>Django Blog - {{ title }}</title>
    {% else %}
    <title>Django Blog</title>
    {% endif %}
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/">Django Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a> <!--URL TAGGING -->
          <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %} <!--if a view returns a message-->
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                  </div>
              {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
</main>

<!-- BOOTSTRAP JS-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

wt2/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block content %}<!--Inherits templates from base with the block called content-->
    <h1>Blog Home!</h1>
    {% for post in posts %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt=":(">  <!--the current post, author of it, image of it and url of it-->
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-detail' post.author.id %}">{{ post.author|capfirst }}</a>
              <small class="text-muted">{{ post.date_posted|date:"d F, Y" }}</small> <!--snippets-->
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title|capfirst }}</a></h2> <!--pk get passed in as url -->
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock %}

wt2/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post {{ object.title }}?</h2>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Confirm</button>
                    <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
                </div>
            </fieldset>
        </form>
    </div>

{% endblock %}

wt2/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}<!--Inherits templates from base with the block called content-->
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}" alt=":(">  <!--the current post, author of it, image of it and url of it-->
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.author }}</a>
              <small class="text-muted">{{ object.date_posted|date:"d F, Y" }}</small> <!--snippets-->
                {% if object.author == user %} <!--if author is the logged in user (author is supposed to be a user type-->
                    <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
          </div>
        </article>
{% endblock %}

wt2/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}<!--uses crispy filter-->
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Post</button>
                </div>
            </fieldset>
        </form>
    </div>

{% endblock %}